# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Commitgen < Formula
  desc "AI-powered commit message generator"
  homepage "https://github.com/FreePeak/commitgen"
  version "0.1.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/FreePeak/commitgen/releases/download/v0.1.4/commitgen_Darwin_x86_64.tar.gz"
      sha256 "007652280684ac9ef8f75a15f88f40f99247c59923dd42dd5d275a660e04770b"

      def install
        bin.install "commitgen"
      end
    end
    on_arm do
      url "https://github.com/FreePeak/commitgen/releases/download/v0.1.4/commitgen_Darwin_arm64.tar.gz"
      sha256 "eb9de69f6f182208dc587680996067f66a681840c1a7ba196051e82b4815b5ff"

      def install
        bin.install "commitgen"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FreePeak/commitgen/releases/download/v0.1.4/commitgen_Linux_x86_64.tar.gz"
        sha256 "affb6c71f90d9768358c01e4c20f9a22580f063b8433501290d9752abd78f216"

        def install
          bin.install "commitgen"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FreePeak/commitgen/releases/download/v0.1.4/commitgen_Linux_arm64.tar.gz"
        sha256 "a5bc4b5a9a5fb34db30cb1fca0c616e8c0117b5f392ee58229b913bcec39ddac"

        def install
          bin.install "commitgen"
        end
      end
    end
  end
end
