# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Commitgen < Formula
  desc "AI-powered commit message generator"
  homepage "https://github.com/FreePeak/commitgen"
  version "0.1.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/FreePeak/commitgen/releases/download/v0.1.3/commitgen_Darwin_x86_64.tar.gz"
      sha256 "b1db2b4db9367a1d72c471148f0425bdad86d562f18fd9455a05d6adf0780537"

      def install
        bin.install "commitgen"
      end
    end
    on_arm do
      url "https://github.com/FreePeak/commitgen/releases/download/v0.1.3/commitgen_Darwin_arm64.tar.gz"
      sha256 "34accfa342eea3293307797fb7b8331288eb30e9eaaaa3afc9d23227ba3c213e"

      def install
        bin.install "commitgen"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FreePeak/commitgen/releases/download/v0.1.3/commitgen_Linux_x86_64.tar.gz"
        sha256 "ed8a5e51032bebb0cabc050eafb46961195b152da14be4fae6a1e9b96aeba599"

        def install
          bin.install "commitgen"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FreePeak/commitgen/releases/download/v0.1.3/commitgen_Linux_arm64.tar.gz"
        sha256 "6847553c81ff1a84ebfde3c1d557edcb29a23e1c40db00a1a7ee536ce36d15de"

        def install
          bin.install "commitgen"
        end
      end
    end
  end
end
