# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Commitgen < Formula
  desc "AI-powered commit message generator"
  homepage "https://github.com/FreePeak/commitgen"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/FreePeak/commitgen/releases/download/v0.1.2/commitgen_Darwin_x86_64.tar.gz"
      sha256 "440ce076bea7918690eb18f399aa5a09aafb5c5634e999933cdf571a25545cc4"

      def install
        bin.install "commitgen"
      end
    end
    on_arm do
      url "https://github.com/FreePeak/commitgen/releases/download/v0.1.2/commitgen_Darwin_arm64.tar.gz"
      sha256 "e144c07a9fe8346a111c6a5b2ed673b0b4f8eea77996926c470666f537206a2a"

      def install
        bin.install "commitgen"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FreePeak/commitgen/releases/download/v0.1.2/commitgen_Linux_x86_64.tar.gz"
        sha256 "3fb442c17bfa43c477a002ac2e61bf19f8b53ed348c36a20c48ab94c7eb15180"

        def install
          bin.install "commitgen"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FreePeak/commitgen/releases/download/v0.1.2/commitgen_Linux_arm64.tar.gz"
        sha256 "c60fcc2daa72ede29fa3d2decd239b007818a26d86f58ca7820b5f9f209d61e0"

        def install
          bin.install "commitgen"
        end
      end
    end
  end
end
